# Generated by Django 3.2.16 on 2024-08-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
    ]
