# Generated by Django 3.2.16 on 2024-08-27 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20240826_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_courses', through='main.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
