# Generated by Django 3.2.16 on 2024-08-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscribers',
        ),
    ]
