services:
    web-app:
        depends_on:
            - database
            - redis
        build:
            context: .
        user: root
        ports:
            - "8000:8000"
        volumes:
            - ./magazin:/magazin
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=pass
            - CELERY_BROKER_URL = 'redis://redis:6379/0'

        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"


    database:
        image: postgres:14.6-alpine
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=pass

    redis:
        image: redis:7.0.5-alpine
        hostname: redis
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
        hostname: worker
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=info
        volumes:
            - ./magazin:/magazin
        links:
            - redis
        depends_on:
            - redis
            - database
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=pass
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0

    worker2:
        build:
            context: .
        hostname: worker2
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=info
        volumes:
            - ./magazin:/magazin
        links:
            - redis
        depends_on:
            - redis
            - database
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=pass
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0

    flower:
        build:
            context: .
        hostname: flower
        entrypoint: celery
        command: -A celery_app.app flower
        volumes:
            - ./magazin:/magazin
        links:
            - redis
        depends_on:
            - redis
        ports:
            - "5555:5555"
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0

